"""add crew for image

Revision ID: 3398e4169a8e
Revises: 87d0cfe9ec65
Create Date: 2025-06-13 22:16:18.886661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3398e4169a8e'
down_revision: Union[str, None] = '87d0cfe9ec65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew_jobs', sa.Column('image_status', sa.String(length=20), nullable=True))
    op.add_column('crew_jobs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crew_jobs', 'updated_at')
    op.drop_column('crew_jobs', 'image_status')
    # ### end Alembic commands ###
