"""add images column

Revision ID: 4423ba6be226
Revises: 3398e4169a8e
Create Date: 2025-06-13 22:31:29.358565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4423ba6be226'
down_revision: Union[str, None] = '3398e4169a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew_jobs', sa.Column('images', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crew_jobs', 'images')
    # ### end Alembic commands ###
